name: Android CI

on:
  push:
    #branches: [ "master" ]
    tags:
      - '*'
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

#    - uses: r0adkll/sign-android-release@v1
#      id: sign_app
#      with:
#        releaseDirectory: app/build/outputs/apk/release
#        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#        alias: ${{ secrets.ALIAS }}
#        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#        keyPassword: ${{ secrets.KEY_PASSWORD }}
      
    - name: Upload Apk
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: release
        path: app/build/outputs/apk/release/app-release.apk
        
    - run: mv app/build/outputs/apk/release/app-release.apk ppx_$GITHUB_REF_NAME.apk
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.apk"
        token: ${{ github.token }}
        generateReleaseNotes: true
